---
deployment:
  tasks:
    # Defina o caminho correto do seu diretório público (ex: public_html para domínio principal)
    - export DEPLOYPATH=/home/$USER/public_html

    # Copia TODO o conteúdo de 'dist', incluindo arquivos ocultos (.htaccess)
    # A sintaxe 'dist/.' é mais segura para incluir arquivos que começam com ponto.
    - /bin/cp -a apps/web/dist/. $DEPLOYPATH/
