---
deployment:
  tasks:
    # Defina o caminho correto do seu diretório público (ex: public_html para domínio principal)
    - export DEPLOYPATH=/home/$USER/public_html

    # Copia os ARQUIVOS COMPILADOS (dist) para o diretório público.
    # Isso requer que a pasta 'dist' tenha sido commitada no repositório.
    - /bin/cp -R apps/web/dist/* $DEPLOYPATH
