---
deployment:
  tasks:
    # AQUI ESTAVA O ERRO! O log mostrou que a pasta certa não é public_html
    - export DEPLOYPATH=/home/$USER/imovelintel.online

    # Copia os arquivos para a pasta CORRETA
    - /bin/cp -f apps/web/dist/index.html $DEPLOYPATH/index.html
    - /bin/cp -f apps/web/dist/.htaccess $DEPLOYPATH/.htaccess
    - /bin/cp -rf apps/web/dist/assets $DEPLOYPATH/
    
    # Permissões
    - /bin/chmod 755 $DEPLOYPATH
    - /usr/bin/find $DEPLOYPATH -type f -exec chmod 644 {} \;
    - /usr/bin/find $DEPLOYPATH -type d -exec chmod 755 {} \;
